In [1]:

import numpy as np                                                 #used for processing arrayobjects and computations on them
import matplotlib.pyplot as plt                                    #used for data visualization
import matplotlib.image as mpimg                                   #image loading and rescaling
import pandas as pd                                                #data analysis and manipulation

import seaborn as sns                                              #high level data visualization
                                                                    #Plot pairwise relationships in a dataset.
                                                                   # It is used to visualize the the distribution of the dataset

from sklearn.metrics import confusion_matrix                       #to check the accuracy of the model developed
from sklearn.metrics import precision_score, recall_score, f1_score

from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import precision_recall_fscore_support
from sklearn.naive_bayes import GaussianNB

In [2]:
# Importing the dataset
dataset = pd.read_csv('forest.csv')

In [3]:
#looking at the first 5 values of the dataset
dataset.head()

b1  b2  b3   b4  b5   b6   b7  b8  b9  pred_minus_obs_H_b1  ...    \
0  67  51  68  115  69  111  136  31  67                47.70  ...     
1  67  28  51   99  50   97   82  26  59                47.93  ...     
2  63  26  50   95  49   91   81  26  57                53.09  ...     
3  63  42  63   97  66  108  111  28  59                52.41  ...     
4  46  27  50   83  51   90   76  26  56                68.54  ...     

   pred_minus_obs_S_b1  pred_minus_obs_S_b2  pred_minus_obs_S_b3  \
0               -18.27                -1.80                -6.32   
1               -20.13                -2.11                -6.35   
2               -17.64                -1.81                -4.70   
3               -20.20                -1.89                -5.47   
4               -18.62                -2.17                -7.11   

   pred_minus_obs_S_b4  pred_minus_obs_S_b5  pred_minus_obs_S_b6  \
0               -20.88                -1.63                -6.13   
1               -21.94                -1.22                -6.13   
2               -19.39                -0.65                -5.01   
3               -21.65                -0.99                -5.71   
4               -21.12                -1.56                -6.35   

   pred_minus_obs_S_b7  pred_minus_obs_S_b8  pred_minus_obs_S_b9  class  
0               -22.56                -5.53                -8.11     d   
1               -22.20                -3.41                -6.57     s   
2               -20.89                -3.96                -6.85     s   
3               -22.19                -3.41                -6.52     d   
4               -22.19                -4.45                -7.32     s   

[5 rows x 28 columns]

In [4]:
from sklearn.preprocessing import LabelEncoder
Enc = LabelEncoder()
data_tf = dataset.copy()
for i in dataset.columns:
   data_tf[i]=Enc.fit_transform(dataset[i])
    
print(data_tf)


     b1  b2  b3  b4  b5  b6  b7  b8  b9  pred_minus_obs_H_b1  ...    \
0    35  27  21  43  25  27  72  12  20                   72  ...     
1    35   5   4  27   6  13  32   7  12                   75  ...     
2    31   3   3  23   5   7  31   7  10                  112  ...     
3    31  19  16  25  22  24  60   9  12                  104  ...     
4    14   4   3  11   7   6  26   7   9                  250  ...     
5    27  34  34  21  26  20  42  10  11                  129  ...     
6    51   5   7  45   7  12  55   8  17                   27  ...     
7    31  14  11  23  14  17  39   8  15                  111  ...     
8    45   6   5  31   7   9  37   8  12                   29  ...     
9    24   9   7  27   6  11  31   5  10                  149  ...     
10   38  29  25  32  29  28  54  11  17                   50  ...     
11   27   6   6  26   8  10  35   8  13                  123  ...     
12   10   6   3  11  10   9  20   6   7                  267  ...     
13   4

In [5]:
#Spliting the dataset in independent and dependent variables

X = data_tf.drop(['class'], axis=1)                                  # all rows first and first 4 columns
y = data_tf['class'].values  


In [6]:

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 82)


**HYPERPARAMETER TUNNING USING GRID SEARCH**

In [7]:


param_grid = {'C': [1, 10, 100, 1000], 'gamma': [1, 0.1, 0.01, 0.001, 0.0001]}
# dictionary for values of parameters C and gamma.
grid = GridSearchCV(SVC(), param_grid, verbose=2)
grid.fit(X_train,y_train)

Fitting 3 folds for each of 20 candidates, totalling 60 fits
[CV] C=1, gamma=1 ....................................................
[CV] ..................................... C=1, gamma=1, total=   0.1s
[CV] C=1, gamma=1 ....................................................
[CV] ..................................... C=1, gamma=1, total=   0.0s
[CV] C=1, gamma=1 ....................................................
[CV] ..................................... C=1, gamma=1, total=   0.0s
[CV] C=1, gamma=0.1 ..................................................
[CV] ................................... C=1, gamma=0.1, total=   0.0s
[CV] C=1, gamma=0.1 ..................................................
[CV] ................................... C=1, gamma=0.1, total=   0.0s
[CV] C=1, gamma=0.1 ..................................................
[CV] ................................... C=1, gamma=0.1, total=   0.0s
[CV] C=1, gamma=0.01 .................................................
[CV] ...........

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s


[CV] ................................. C=1, gamma=0.001, total=   0.0s
[CV] C=1, gamma=0.001 ................................................
[CV] ................................. C=1, gamma=0.001, total=   0.0s
[CV] C=1, gamma=0.001 ................................................
[CV] ................................. C=1, gamma=0.001, total=   0.0s
[CV] C=1, gamma=0.0001 ...............................................
[CV] ................................ C=1, gamma=0.0001, total=   0.0s
[CV] C=1, gamma=0.0001 ...............................................
[CV] ................................ C=1, gamma=0.0001, total=   0.0s
[CV] C=1, gamma=0.0001 ...............................................
[CV] ................................ C=1, gamma=0.0001, total=   0.0s
[CV] C=10, gamma=1 ...................................................
[CV] .................................... C=10, gamma=1, total=   0.0s
[CV] C=10, gamma=1 ...................................................
[CV] .

[Parallel(n_jobs=1)]: Done  60 out of  60 | elapsed:    1.3s finished


GridSearchCV(cv=None, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'C': [1, 10, 100, 1000], 'gamma': [1, 0.1, 0.01, 0.001, 0.0001]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=2)

In [8]:
grid.best_params_

{'C': 10, 'gamma': 0.0001}

In [9]:
grid_predictions = grid.predict(X_test)

In [460]:
print(grid_predictions)

[3 1 1 3 3 2 3 0 3 3 3 0 0 0 3 0 3 3 1 0 3 3 3 3 3 0 3 3 0 3 3 3 0 0 3 3 3
 3 3 3 3 3 3 0 0 3 3 3 0 0 3 3 0 3 3 0 0 3 3 0]


**MODEL EVELUATION**

In [461]:
print(confusion_matrix(y_test,grid_predictions))

[[12  0  0  3]
 [ 1  3  0  5]
 [ 2  0  1  6]
 [ 3  0  0 24]]


In [462]:
print(classification_report(y_test,grid_predictions))

              precision    recall  f1-score   support

           0       0.67      0.80      0.73        15
           1       1.00      0.33      0.50         9
           2       1.00      0.11      0.20         9
           3       0.63      0.89      0.74        27

    accuracy                           0.67        60
   macro avg       0.82      0.53      0.54        60
weighted avg       0.75      0.67      0.62        60



In [463]:




# Splitting the dataset into the Training set and Test set
#   x_train is the       :---> training data set.
#  y_train is the        :---> set of labels to all the data in x_train.
#your model after the model has gone through initial vetting by the validation set.
#x_test is the test data set.
#y_test is the set of labels to all the data in x_test.



In [464]:

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()


# Feature Scaling to bring the variable in a single scale
# scaling happen independently on each feature by computing the relevant statistics on the samples in the training set



X_train = sc.fit_transform(X_train)   #Fit to data, then transform it.
X_test = sc.transform(X_test)         #Perform standardization(rescaling original data without changing the nature)
                                        #by centering and scaling

# Using Linear Kernel.

In [465]:
# Fitting SVC Classification to the Training set with linear kernel
# Kernal Function : xi * xj


from sklearn.svm import SVC

svcclassifier1 = SVC(kernel = 'linear', random_state = 0)
svcclassifier1.fit(X_train, y_train)




SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=0,
    shrinking=True, tol=0.001, verbose=False)

In [466]:
# Predicting the Test set results



x_pred1 = svcclassifier1.predict(X_train)
y_pred1 = svcclassifier1.predict(X_test)
print(y_pred1)

[3 1 1 3 3 2 1 0 0 3 3 0 0 0 0 0 0 3 1 0 2 2 3 3 3 0 2 3 0 3 3 0 0 0 3 3 3
 3 3 3 3 1 3 0 0 3 3 3 0 0 2 3 0 1 3 3 0 3 3 0]


In [467]:
#lets see the actual and predicted value side by side

y_compare1 = np.vstack((y_test,y_pred1)).T


#actual value on the left side and predicted value on the right hand side
#printing the top 5 values

y_compare1[:5,:]



array([[3, 3],
       [1, 1],
       [1, 1],
       [1, 3],
       [3, 3]])

In [468]:
# Making the Confusion Matrix
print('*********FOR LINEAR KERNAL*********')

ac1=accuracy_score(y_test, y_pred1)
print('\n Testing Accuracy of SVM using Linear Kernel :',ac1*100,end='%')

tac1 = accuracy_score(y_train, x_pred1)
print('\n Training Accuracy of SVM using Linear Kernal :',tac1*100,end='%')



print('\n1) Confusion Matrix:  ')

cm1 = confusion_matrix(y_test, y_pred1)
print(cm1)

print('\n2) Shape of Confusion Matrix')
a1 = cm1.shape
print(a1)


corrPred1 = 0
falsePred1 = 0

for row1 in range(a1[0]):
    for c1 in range(a1[1]):
        if row1 == c1:
            corrPred1 +=cm1[row1,c1]
        else:
            falsePred1 += cm1[row1,c1]
     
  
print('\n3) Correct predictions:  ', corrPred1)
print('\n4)False predictions: ', falsePred1)
kernelLinearAccuracy = corrPred1/(cm1.sum())


print("\n5)Precision Score:  {0:.4f}".format(precision_score(y_test, y_pred1,average='weighted'))) 
                                                           
print("\n6)Recall Score: {0:.4f}".format(recall_score(y_test, y_pred1, average='weighted'))) 
                                                    
                                                    
print("\n7)F1 Score: {0:.4f}".format(f1_score(y_test,y_pred1,  average='weighted'))) 
                                           

print ('\n8)Accuracy of the SVC Clasification (USING LINEAR KERNAL)is: ', kernelLinearAccuracy*100,end='%')        



*********FOR LINEAR KERNAL*********

 Testing Accuracy of SVM using Linear Kernel : 80.0%
 Training Accuracy of SVM using Linear Kernal : 92.37288135593221%
1) Confusion Matrix:  
[[14  0  0  1]
 [ 0  6  0  3]
 [ 3  0  5  1]
 [ 4  0  0 23]]

2) Shape of Confusion Matrix
(4, 4)

3) Correct predictions:   48

4)False predictions:  12

5)Precision Score:  0.8363

6)Recall Score: 0.8000

7)F1 Score: 0.7980

8)Accuracy of the SVC Clasification (USING LINEAR KERNAL)is:  80.0%

# Using polynomial kernel

In [469]:
# Fitting SVC Classification to the Training set with linear kernel
# Kernal Function = (xi*xj+1)^d


from sklearn.svm import SVC

svcclassifier2 = SVC(kernel = 'poly', random_state = 0)
svcclassifier2.fit(X_train, y_train)

# Predicting the Test set results
x_pred2 = svcclassifier2.predict(X_train)
y_pred2 = svcclassifier2.predict(X_test)
print(y_pred2)

[3 1 1 3 3 2 3 0 0 3 3 3 0 0 0 0 3 3 1 0 0 2 3 3 3 0 0 3 3 3 3 0 0 3 3 3 3
 3 3 3 3 3 3 3 0 3 3 3 0 0 2 3 0 1 3 3 0 3 3 3]


In [470]:
#lets see the actual and predicted value side by side
y_compare2 = np.vstack((y_test,y_pred2)).T
#actual value on the left side and predicted value on the right hand side
#printing the top 5 values
y_compare2[:5,:]

array([[3, 3],
       [1, 1],
       [1, 1],
       [1, 3],
       [3, 3]])

In [471]:
print('*********FOR POLYNOMIAL KERNAL*********')

ac2=accuracy_score(y_test, y_pred2)
print('\n Testing Accuracy of SVM using Polynomial Kernel :',ac2*100,end='%')

tac2 = accuracy_score(y_train, x_pred2)
print('\n Training Accuracy of SVM using Polynomial Kernal :',tac2*100,end='%')



print('\n1) Confusion Matrix:  ')

cm2 = confusion_matrix(y_test, y_pred2)
print(cm2)

print('\n2) Shape of Confusion Matrix')
a2 = cm2.shape
print(a2)


corrPred2 = 0
falsePred2 = 0

for row2 in range(a2[0]):
    for c2 in range(a2[1]):
        if row2 == c2:
            corrPred2 +=cm2[row2,c2]
        else:
            falsePred2 += cm2[row2,c2]
     
  
print('\n3) Correct predictions:  ', corrPred2)
print('\n4)False predictions: ', falsePred2)

kernelPolyAccuracy = corrPred2/(cm2.sum())

print("\n5)Precision Score:  {0:.4f}".format(precision_score(y_test, y_pred2,average='weighted'))) 
                                                           
print("\n6)Recall Score: {0:.4f}".format(recall_score(y_test, y_pred2, average='weighted'))) 
                                                    
                                                    
print("\n7)F1 Score: {0:.4f}".format(f1_score(y_test,y_pred2,  average='weighted'))) 
                                           

print ('\n8)Accuracy of the SVC Clasification (using Polynomial kernal)is: ', kernelPolyAccuracy*100,end='%')        



*********FOR POLYNOMIAL KERNAL*********

 Testing Accuracy of SVM using Polynomial Kernel : 70.0%
 Training Accuracy of SVM using Polynomial Kernal : 89.83050847457628%
1) Confusion Matrix:  
[[10  0  0  5]
 [ 0  4  0  5]
 [ 5  0  3  1]
 [ 2  0  0 25]]

2) Shape of Confusion Matrix
(4, 4)

3) Correct predictions:   42

4)False predictions:  18

5)Precision Score:  0.7596

6)Recall Score: 0.7000

7)F1 Score: 0.6807

8)Accuracy of the SVC Clasification (using Polynomial kernal)is:  70.0%

# Using rbf kernel

In [472]:
# Fitting SVC Classification to the Training set with linear kernel
# The input space can be mapped in infinite dimensional space by RBF kernal


from sklearn.svm import SVC


svcclassifier3 = SVC(kernel = 'rbf', random_state = 0)
svcclassifier3.fit(X_train, y_train)

# Predicting the Test set results
x_pred3 = svcclassifier3.predict(X_train)
y_pred3 = svcclassifier3.predict(X_test)
print(y_pred3)

[3 1 1 3 3 2 1 0 0 3 3 0 0 0 0 0 0 3 1 0 2 2 3 3 3 0 2 3 0 3 3 0 0 1 3 1 3
 3 3 3 3 3 3 3 0 3 3 3 0 0 2 3 0 1 3 3 0 3 0 0]


In [473]:
#lets see the actual and predicted value side by side
y_compare3 = np.vstack((y_test,y_pred3)).T
#actual value on the left side and predicted value on the right hand side
#printing the top 5 values
y_compare3[:5,:]

array([[3, 3],
       [1, 1],
       [1, 1],
       [1, 3],
       [3, 3]])

In [474]:

print('*********FOR RBF KERNAL*********')

ac3=accuracy_score(y_test, y_pred3)
print('\n Testing Accuracy of SVM using RBF Kernel :',ac3*100,end='%')

tac3 = accuracy_score(y_train, x_pred3)
print('\n Training Accuracy of SVM using RBF Kernal :',tac3*100,end='%')



print('\n1) Confusion Matrix:  ')

cm3 = confusion_matrix(y_test, y_pred3)
print(cm3)

print('\n2) Shape of Confusion Matrix')
a3 = cm3.shape
print(a3)


corrPred3 = 0
falsePred3 = 0

for row3 in range(a3[0]):
    for c3 in range(a3[1]):
        if row3 == c3:
            corrPred3 +=cm3[row3,c3]
        else:
            falsePred3 += cm3[row3,c3]
     
  
print('\n3) Correct predictions:  ', corrPred3)
print('\n4)False predictions: ', falsePred3)

kernelRbfAccuracy = corrPred3/(cm3.sum())

print("\n5)Precision Score:  {0:.4f}".format(precision_score(y_test, y_pred3,average='weighted'))) 
                                                           
print("\n6)Recall Score: {0:.4f}".format(recall_score(y_test, y_pred3, average='weighted'))) 
                                                    
                                                    
print("\n7)F1 Score: {0:.4f}".format(f1_score(y_test,y_pred3,  average='weighted'))) 
                                           

print ( 'Accuracy of the SVC Clasification (using rbf kernal) is: ', kernelRbfAccuracy*100)



*********FOR RBF KERNAL*********

 Testing Accuracy of SVM using RBF Kernel : 81.66666666666667%
 Training Accuracy of SVM using RBF Kernal : 92.79661016949152%
1) Confusion Matrix:  
[[14  0  0  1]
 [ 0  6  0  3]
 [ 4  0  5  0]
 [ 2  1  0 24]]

2) Shape of Confusion Matrix
(4, 4)

3) Correct predictions:   49

4)False predictions:  11

5)Precision Score:  0.8393

6)Recall Score: 0.8167

7)F1 Score: 0.8124
Accuracy of the SVC Clasification (using rbf kernal) is:  81.66666666666667


# Using sigmoid kernel 

In [475]:
# Fitting SVC Classification to the Training set with sigmoid kernel


from sklearn.svm import SVC

svcclassifiers4 = SVC(kernel = 'sigmoid', random_state = 0)
svcclassifiers4.fit(X_train, y_train)

# Predicting the Test set results

x_pred4 = svcclassifiers4.predict(X_train)
y_pred4 = svcclassifiers4.predict(X_test)
print(y_pred4)





[3 1 1 3 3 0 1 0 0 3 3 0 0 0 0 0 0 3 1 0 0 2 3 3 3 0 2 1 3 3 3 0 0 1 3 1 3
 3 3 3 3 3 3 3 0 3 3 3 0 0 2 3 0 1 3 3 0 3 3 0]


In [476]:
#lets see the actual and predicted value side by side
y_compare4 = np.vstack((y_test,y_pred4)).T
#actual value on the left side and predicted value on the right hand side
#printing the top 5 values
y_compare4[:5,:]

array([[3, 3],
       [1, 1],
       [1, 1],
       [1, 3],
       [3, 3]])

In [477]:

print('*********FOR SIGMOID KERNAL*********')

ac4=accuracy_score(y_test, y_pred4)
print('\n Testing Accuracy of SVM using Sigmoid Kernel :',ac4*100,end='%')

tac4 = accuracy_score(y_train, x_pred3)
print('\n Training Accuracy of SVM using Sigmoid Kernal :',tac4*100,end='%')



print('\n1) Confusion Matrix:  ')

cm4 = confusion_matrix(y_test, y_pred4)
print(cm4)

print('\n2) Shape of Confusion Matrix')
a4 = cm4.shape
print(a4)


corrPred4 = 0
falsePred4 = 0

for row4 in range(a4[0]):
    for c4 in range(a4[1]):
        if row4 == c4:
            corrPred4 +=cm4[row4,c4]
        else:
            falsePred4 += cm3[row4,c4]
     
  
print('\n3) Correct predictions:  ', corrPred4)
print('\n4)False predictions: ', falsePred4)

kernelSfAccuracy = corrPred4/(cm4.sum())

print("\n5)Precision Score:  {0:.4f}".format(precision_score(y_test, y_pred4,average='weighted'))) 
                                                           
print("\n6)Recall Score: {0:.4f}".format(recall_score(y_test, y_pred4, average='weighted'))) 
                                                    
                                                    
print("\n7)F1 Score: {0:.4f}".format(f1_score(y_test,y_pred4,  average='weighted'))) 
                                           

print ( 'Accuracy of the SVC Clasification (using Sigmoid kernal) is: ', kernelSfAccuracy*100)


*********FOR SIGMOID KERNAL*********

 Testing Accuracy of SVM using Sigmoid Kernel : 75.0%
 Training Accuracy of SVM using Sigmoid Kernal : 92.79661016949152%
1) Confusion Matrix:  
[[13  0  0  2]
 [ 0  6  0  3]
 [ 5  0  3  1]
 [ 2  2  0 23]]

2) Shape of Confusion Matrix
(4, 4)

3) Correct predictions:   45

4)False predictions:  11

5)Precision Score:  0.7819

6)Recall Score: 0.7500

7)F1 Score: 0.7362
Accuracy of the SVC Clasification (using Sigmoid kernal) is:  75.0


In [481]:
# Decision Tree
print("\n-------------------------------------------------------")
print("\t\t\tDecision Tree")

model_DecisionTree = DecisionTreeClassifier()
model_DecisionTree.fit(X_train, y_train)
y_predict=model_DecisionTree.predict(X_test)
X_predict = model_DecisionTree.predict(X_train)
print("\nConfusion matrix for decision tree classifier : ")
print(confusion_matrix(y_test,y_predict))

a4 = cm4.shape
print(a4)


corrPred4 = 0
falsePred4 = 0

for row4 in range(a4[0]):
    for c4 in range(a4[1]):
        if row4 == c4:
            corrPred4 +=cm4[row4,c4]
        else:
            falsePred4 += cm3[row4,c4]
     
  
print('\n3) Correct predictions:  ', corrPred4)
print('\n4)False predictions: ', falsePred4)






print('\n Testing Accuracy for Decision Tree :',ac*100,end='%')
tac=accuracy_score(y_train, X_predict)
print('\n Training Accuracy for Decision Tree :',tac*100,end='%')
pre=precision_recall_fscore_support(y_test, y_predict) 
#print(pre)
print("\n7)F1 Score: {0:.4f}".format(f1_score(y_test,y_predict,  average='weighted'))) 

a4 = cm4.shape
print(a4)


corrPred4 = 0
falsePred4 = 0

for row4 in range(a4[0]):
    for c4 in range(a4[1]):
        if row4 == c4:
            corrPred4 +=cm4[row4,c4]
        else:
            falsePred4 += cm3[row4,c4]
     
  
print('\n3) Correct predictions:  ', corrPred4)
print('\n4)False predictions: ', falsePred4)
print("\n\nPrecision for Decision Tree : ",pre[0][0])
#print(pre[0][0]) #precision   (tp/(tp+fp)
print("\nRecall for Decision Tree : ",pre[1][0])
#print(pre[1][0]) #Recall     (tp/tp+fn)
print("\n-------------------------------------------------------")

# Logistic regression
print("\n-------------------------------------------------------")
print("\t\t\tLogistic Regression")
clf = LogisticRegression(random_state=0, solver='newton-cg', multi_class='multinomial').fit(X_train, y_train)
y_pred = clf.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print('\nConfusion matrix for Logistic Regression : ')
print(cm)
#score = clf.score(y_test,y_pred)
score = clf.score(X_test,y_test)
print('\nTesting Accuracy for Logistic Regression :',score*100,end='%')
tscore = clf.score(X_train,y_train)



a4 = cm4.shape
print(a4)


corrPred4 = 0
falsePred4 = 0

for row4 in range(a4[0]):
    for c4 in range(a4[1]):
        if row4 == c4:
            corrPred4 +=cm4[row4,c4]
        else:
            falsePred4 += cm3[row4,c4]
     
  
print('\n3) Correct predictions:  ', corrPred4)
print('\n4)False predictions: ', falsePred4)

print("\n7)F1 Score: {0:.4f}".format(f1_score(y_test,y_pred,  average='weighted'))) 
print('\nTraining Accuracy for Logistic Regression :',tscore*100,end='%')
pre = precision_recall_fscore_support(y_test, y_predict) 
#print(pre)
print("\n\nPrecision for Logistic Regression : ",pre[0][0])
#print(pre[0][0]) #precision   (tp/(tp+fp)
print("\nRecall for Logistic Regression : ",pre[1][0])
#print(pre[1][0]) #Recall     (tp/tp+fn)
print("\n-------------------------------------------------------")



-------------------------------------------------------
			Decision Tree

Confusion matrix for decision tree classifier : 
[[10  1  0  4]
 [ 0  7  0  2]
 [ 2  1  6  0]
 [ 6  3  1 17]]

 Testing Accuracy for Decision Tree : 66.66666666666666%
 Training Accuracy for Decision Tree : 100.0%
7)F1 Score: 0.6700


Precision for Decision Tree :  0.5555555555555556

Recall for Decision Tree :  0.6666666666666666

-------------------------------------------------------

-------------------------------------------------------
			Logistic Regression

Confusion matrix for Logistic Regression : 
[[13  1  0  1]
 [ 0  6  0  3]
 [ 2  1  5  1]
 [ 2  1  0 24]]

Testing Accuracy for Logistic Regression : 80.0%
7)F1 Score: 0.7960

Training Accuracy for Logistic Regression : 90.67796610169492%

Precision for Logistic Regression :  0.5555555555555556

Recall for Logistic Regression :  0.6666666666666666

-------------------------------------------------------


In [482]:
# Naive Bayes
#print("\n\nNaive Bayes")
s=StandardScaler()
#z-score normalization values in 0,1 format
x_scale = s.fit_transform(X)

classifier = GaussianNB()
classifier.fit(X_train,y_train)
#fitting data and trying to predict test data

x_predict = classifier.predict(X_train)
y_predict = classifier.predict(X_test)
cm = confusion_matrix(y_test,y_predict)
print("\n------------------------------------------------------------")
print("\t\t\tNaive Bayes")
print("\nConfusion matrix for Naive Bayes classifier : ")
print(cm)
ac = accuracy_score(y_test,y_predict)
print('\nTesting Accuracy for Naive Bayes :',ac*100,end='%')
tac= accuracy_score(y_train, x_predict)
print('\nTraining Accuracy for Naive Bayes :',tac*100,end='%')



a4 = cm4.shape
print(a4)


corrPred4 = 0
falsePred4 = 0

for row4 in range(a4[0]):
    for c4 in range(a4[1]):
        if row4 == c4:
            corrPred4 +=cm4[row4,c4]
        else:
            falsePred4 += cm3[row4,c4]
     
  
print('\n3) Correct predictions:  ', corrPred4)
print('\n4)False predictions: ', falsePred4)
pre=precision_recall_fscore_support(y_test, y_predict) 
print("\n7)F1 Score: {0:.4f}".format(f1_score(y_test,y_predict,  average='weighted'))) 
#print(pre)
print("\nPrecision for Naive Bayes classifier : ",pre[0][0])
#print(pre[0][0]) #precision   (tp/(tp+fp)
print("\nRecall for Naive Bayes classifier : ",pre[1][0])
#print(pre[1][0]) #Recall     (tp/tp+fn)
print("\n------------------------------------------------------------")



------------------------------------------------------------
			Naive Bayes

Confusion matrix for Naive Bayes classifier : 
[[11  0  1  3]
 [ 0  7  0  2]
 [ 3  0  6  0]
 [ 3  4  0 20]]

Testing Accuracy for Naive Bayes : 73.33333333333333%
Training Accuracy for Naive Bayes : 81.77966101694916%(4, 4)

3) Correct predictions:   45

4)False predictions:  11

7)F1 Score: 0.7355

Precision for Naive Bayes classifier :  0.6470588235294118

Recall for Naive Bayes classifier :  0.7333333333333333

------------------------------------------------------------
